name: Sync Fork

on:
  schedule:
    - cron: "30 08 * * *" 
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: setup
        run: |
          git config user.name "Anurag Kumar"
          git config user.email "anuragxone@outlook.in"

      - name: upstream
        run: |
          git remote add lineage https://github.com/LineageOS/android_packages_apps_Twelve.git
          git fetch lineage

      - name: sync
        run: |
          git checkout main
          git merge lineage/lineage-22.1

      - name: push
        run: git push https://anuragxone:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main